#!/bin/bash

# Use this script to copy the mesh files to the renderer directory.
# Just go to the shape output directory and run this script.
# Go to the url where index.html is being served to see the 3d render.

cp resliced_mesh* /usr/local/shape/viewer/
